tap "bradyjoslin/sharewifi"
tap "cloudflare/cloudflare"
tap "fwartner/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ngrok/ngrok"
tap "planetscale/tap"
tap "thoughtbot/formulae"
brew "asdf"
brew "broot"
brew "python@3.9"
brew "cairo"
brew "chezmoi"
brew "unbound"
brew "qemu"
brew "lima"
brew "colima"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "folly"
brew "edencommon"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "harfbuzz"
brew "libarchive"
brew "libass"
brew "libbluray"
brew "pango"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "ghostscript"
brew "git-delta"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "ktlint"
brew "librsvg"
brew "mas"
brew "mitmproxy"
brew "node"
brew "openslide"
brew "poppler"
brew "procs"
brew "python@3.10"
brew "shellcheck"
brew "starship"
brew "swiftformat"
brew "tokei"
brew "vips"
brew "watchman"
brew "xh"
brew "zoxide"
brew "bradyjoslin/sharewifi/sharewifi"
brew "cloudflare/cloudflare/cloudflared"
brew "fwartner/tap/mac-cleanup"
brew "planetscale/tap/pscale"
cask "1password"
cask "1password-cli"
cask "aerial"
cask "alt-tab"
cask "android-file-transfer"
cask "android-platform-tools"
cask "android-sdk"
cask "android-studio"
cask "appcleaner"
cask "around"
cask "bartender"
cask "blockblock"
cask "cleanshot"
cask "cloudflare-warp"
cask "envkey"
cask "figma"
cask "font-victor-mono"
cask "font-victor-mono-nerd-font"
cask "fork"
cask "github"
cask "glance"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "height"
cask "hyperkey"
cask "iina"
cask "imageoptim"
cask "iterm2"
cask "keyboard-cleaner"
cask "knockknock"
cask "linear-linear"
cask "loom"
cask "lulu"
cask "maintenance"
cask "microsoft-auto-update"
cask "microsoft-word"
cask "mimestream"
cask "monitorcontrol"
cask "mullvadvpn"
cask "musaicfm"
cask "ngrok"
cask "notion"
cask "omnidisksweeper"
cask "permute"
cask "pictogram"
cask "pika"
cask "pine"
cask "pocket-casts"
cask "porting-kit"
cask "postgres-unofficial"
cask "postman"
cask "proxyman"
cask "raycast"
cask "rescuetime"
cask "rotato"
cask "secretive"
cask "shifty"
cask "shottr"
cask "silentknight"
cask "skype"
cask "slack"
cask "spotify"
cask "stats"
cask "steam"
cask "stremio"
cask "superhuman"
cask "tableplus"
cask "telegram"
cask "transmission"
cask "tuple"
cask "visual-studio-code"
cask "warp"
cask "webtorrent"
cask "whatsapp"
cask "zoom"
mas "Battery Indicator", id: 1206020918
mas "Broadcasts", id: 1469995354
mas "Craft", id: 1487937127
mas "Cursor Pro", id: 1447043133
mas "Darkroom", id: 953286746
mas "Dato", id: 1470584107
mas "Ferromagnetic", id: 1546537151
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "Intermission", id: 1439431081
mas "Keynote", id: 409183694
mas "Lungo", id: 1263070803
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pandan", id: 1569600264
mas "Pause", id: 1599313358
mas "rcmd", id: 1596283165
mas "Shazam", id: 897118787
mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "Triode", id: 1450027401
mas "Twitter", id: 1482454543
mas "Uno", id: 1584884476
mas "WiFi Signal", id: 525912054
mas "Xcode", id: 497799835
vscode "adpyke.vscode-sql-formatter"
vscode "bmalehorn.vscode-fish"
vscode "bradlc.vscode-tailwindcss"
vscode "Cardinal90.multi-cursor-case-preserve"
vscode "cesium.gltf-vscode"
vscode "chrislajoie.vscode-modelines"
vscode "cstef.kotlin-formatter"
vscode "dbaeumer.vscode-eslint"
vscode "dnicolson.binary-plist"
vscode "dotenv.dotenv-vscode"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "GitHub.copilot-labs"
vscode "GitHub.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "GraphQL.vscode-graphql"
vscode "GraphQL.vscode-graphql-syntax"
vscode "IBM.output-colorizer"
vscode "jasonnutter.search-node-modules"
vscode "jmfirth.vsc-space-block-jumper"
vscode "johnpapa.vscode-peacock"
vscode "mathiasfrohlich.Kotlin"
vscode "mikestead.dotenv"
vscode "mrorz.language-gettext"
vscode "Prisma.prisma"
vscode "pveyes.aperture"
vscode "qinjia.seti-icons"
vscode "richie5um2.vscode-sort-json"
vscode "sidneys1.gitconfig"
vscode "spywhere.mark-jump"
vscode "sswg.swift-lang"
vscode "stkb.rewrap"
vscode "timonwong.shellcheck"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "vknabel.vscode-swiftformat"
vscode "WakaTime.vscode-wakatime"
vscode "will-stone.plastic"
vscode "yoavbls.pretty-ts-errors"
