tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "ngrok/ngrok"
tap "peterldowns/tap"
tap "potatolabs/git-redate"
tap "roots/tap"
tap "smudge/smudge"
tap "xcodesorg/made"
brew "bat"
brew "chezmoi"
brew "curl"
brew "libpq"
brew "php"
brew "composer"
brew "direnv"
brew "doctl"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fisher"
brew "flyctl"
brew "fzf"
brew "git"
brew "mas"
brew "mise"
brew "node"
brew "openfortivpn"
brew "procs"
brew "shellcheck"
brew "sleepwatcher", restart_service: :changed
brew "starship"
brew "tokei"
brew "webtorrent-cli"
brew "xh"
brew "zoxide"
brew "peterldowns/tap/localias", link: false
brew "potatolabs/git-redate/git-redate"
brew "roots/tap/trellis-cli"
brew "smudge/smudge/nightlight"
brew "xcodesorg/made/xcodes"
cask "1password"
cask "android-studio"
cask "appcleaner"
cask "blockblock"
cask "cleanshot"
cask "cloudflare-warp"
cask "figma"
cask "font-victor-mono"
cask "font-victor-mono-nerd-font"
cask "fork"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "iina"
cask "imageoptim"
cask "keka"
cask "knockknock"
cask "lulu"
cask "microsoft-word"
cask "mullvad-vpn"
cask "ngrok"
cask "obsidian"
cask "omnidisksweeper"
cask "orbstack"
cask "porting-kit"
cask "raycast"
cask "remote-buddy"
cask "slack"
cask "spotify"
cask "stats"
cask "tableplus"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
cask "whatsapp"
cask "zulu@17"
mas "Autostarter", id: 6444444273
mas "Broadcasts", id: 1469995354
mas "Dato", id: 1470584107
mas "Keynote", id: 409183694
mas "Lungo", id: 1263070803
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pandan", id: 1569600264
mas "WiFi Signal", id: 525912054
vscode "bmalehorn.vscode-fish"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "mrorz.language-gettext"
vscode "orta.vscode-twoslash-queries"
vscode "prisma.prisma"
vscode "pucelle.run-on-save"
vscode "timonwong.shellcheck"
vscode "vscode-icons-team.vscode-icons"
vscode "will-stone.plastic"
