tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "thoughtbot/formulae"
brew "broot"
brew "chezmoi"
brew "direnv"
brew "fish"
brew "fzf"
brew "git-delta"
brew "gitui"
brew "gmailctl"
brew "iconsur"
brew "mas"
brew "n"
brew "shellcheck"
brew "starship"
brew "zoxide"
brew "zsh"
brew "thoughtbot/formulae/gitsh"
cask "1password-cli"
cask "aerial"
cask "appcleaner"
cask "around"
cask "blockblock"
cask "cleanshot"
cask "cloudflare-warp"
cask "contexts"
cask "discord"
cask "dozer"
cask "dropbox"
cask "envkey"
cask "figma"
cask "font-victor-mono"
cask "fork"
cask "glance"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iina"
cask "imageoptim"
cask "iterm2"
cask "keyboard-cleaner"
cask "keyboard-maestro"
cask "knockknock"
cask "linear-linear"
cask "loom"
cask "lulu"
cask "maintenance"
cask "monitorcontrol"
cask "notion"
cask "omnidisksweeper"
cask "permute"
cask "pika"
cask "pine"
cask "pocket-casts"
cask "porting-kit"
cask "raycast"
cask "rectangle"
cask "rescuetime"
cask "shifty"
cask "silentknight"
cask "skype"
cask "slack"
cask "spotify"
cask "stats"
cask "steam"
cask "superhuman"
cask "telegram"
cask "tuple"
cask "visual-studio-code"
cask "webcatalog"
cask "webtorrent"
cask "whatsapp"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "Aware", id: 1082170746
mas "Broadcasts", id: 1469995354
mas "Cursor Pro", id: 1447043133
mas "Dato", id: 1470584107
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "Shazam", id: 897118787
mas "Speedtest", id: 1153157709
mas "Twitter", id: 1482454543
mas "WiFi Signal", id: 525912054
