# Zsh configuration
DEFAULT_USER="yenbekbay"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE=true
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')

# Unix aliases
alias e="$EDITOR"
alias mkdir="mkdir -p"

# Mac OS X aliases
alias unhidelibrary="chflags nohidden ~/Library"
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Replacements
alias ls="k -h"
alias lss="ls -ah"
alias rm=trash

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

# Other aliases
alias dotfiles="rcup -v -d ~/.dotfiles/symlinks"
alias ip="curl ipinfo.io/ip"

# Do not record an event that was just recorded again
setopt hist_ignore_dups

# Delete an old recorded event if a new event is a duplicate
setopt hist_ignore_all_dups
setopt hist_save_nodups

# Expire a duplicate event first when trimming history
setopt hist_expire_dups_first

# Do not display a previously found event
setopt hist_find_no_dups

# Share history
setopt share_history

# Pack extra blank
setopt hist_reduce_blanks

# Write to the history file immediately, not when the shell exits
setopt inc_append_history

# Remove comannd of 'hostory' or 'fc -l' from history list
setopt hist_no_store

# Remove functions from history list
setopt hist_no_functions

# Record start and end time to history file
setopt extended_history

# Ignore the beginning space command to history file
setopt hist_ignore_space

# Append to history file
setopt append_history

# Edit history file during call history before executing
setopt hist_verify

# Enable history system like a Bash
setopt bang_hist

# Expand parameters and substitude commands in prompts
setopt prompt_subst

# Initialize zplug
source ~/.zplug/init.zsh

# Local plugins
zplug "~/.zsh", from:local, use:"*.zsh"

# Oh-my-zsh plugins
zplug "plugins/brew-cask", from:oh-my-zsh, nice:10
zplug "plugins/brew", from:oh-my-zsh
zplug "plugins/bundler", from:oh-my-zsh
zplug "plugins/gem", from:oh-my-zsh
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh, nice:10
zplug "plugins/heroku", from:oh-my-zsh
zplug "plugins/httpie", from:oh-my-zsh, nice:10
zplug "plugins/node", from:oh-my-zsh
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/osx", from:oh-my-zsh
zplug "plugins/pip", from:oh-my-zsh
zplug "plugins/pod", from:oh-my-zsh
zplug "plugins/python", from:oh-my-zsh
zplug "plugins/ruby", from:oh-my-zsh
zplug "plugins/z", from:oh-my-zsh

# Remote plugins
zplug "atweiden/fzf-extras", use:"*.{zsh,sh}"
zplug "supercrabtree/k"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting", nice:10

# Install missing plugins
if ! zplug check --verbose; then
  echo; zplug install
fi

# Source installed plugins
zplug load

# Bind up and down keys for zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Activate python environment
eval "$(pyenv init -)"

# Activate ruby environment
eval "$(rbenv init -)"

# Activate node environment
source $(brew --prefix nvm)/nvm.sh

# Activate fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
