DEFAULT_USER="yenbekbay"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE=true
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')

source ~/.zplug/init.zsh

zplug "plugins/brew-cask", from:oh-my-zsh, nice:10
zplug "plugins/brew", from:oh-my-zsh
zplug "plugins/bundler", from:oh-my-zsh
zplug "plugins/gem", from:oh-my-zsh
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh, nice:10
zplug "plugins/heroku", from:oh-my-zsh
zplug "plugins/httpie", from:oh-my-zsh, nice:10
zplug "plugins/node", from:oh-my-zsh
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/osx", from:oh-my-zsh
zplug "plugins/pip", from:oh-my-zsh
zplug "plugins/pod", from:oh-my-zsh
zplug "plugins/python", from:oh-my-zsh
zplug "plugins/ruby", from:oh-my-zsh
zplug "plugins/z", from:oh-my-zsh

zplug "junegunn/fzf-bin", as:command, from:gh-r, rename-to:"fzf", frozen:1
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "zsh-users/zsh-completions"
zplug "supercrabtree/k"
zplug "b4b4r07/enhancd", use:enhancd.sh

if ! zplug check --verbose; then
  echo; zplug install
fi

zplug load

source ~/.zsh/aliases.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/options.zsh
source ~/.zsh/prompt.zsh

eval "$(pyenv init -)"
eval "$(rbenv init -)"
source $(brew --prefix nvm)/nvm.sh
